#!/bin/sh
#
# Run the lbdb testsuite
#
# (c) 2018 Roland Rosenfeld <roland@debian.org>

echo "Running dh_auto_configure"
dh_auto_configure >/dev/null 2>&1

echo "Running testsuite"
cd tests
./testsuite
